### ISSUE TITLE
the template_file_compare.py always show same error of  Incorrect packet data when run,why?and the other examples run brilliant.

### ISSUE THREAD

**Issue by Chenuuuu** [adafruit/Adafruit_CircuitPython_Fingerprint#45]
INFO: Sensor les not support LED. Error: Incorrect packet data
Place finger on sensor...Traceback (most recent call last):
  File "/home/pi/Desktop/adafruit_finger_compared.py", line 192, in <module>
    enroll_save_to_file()
  File "/home/pi/Desktop/adafruit_finger_compared.py", line 91, in enroll_save_to_file
    i = finger.get_image()
  File "/usr/local/lib/python3.9/dist-packages/adafruit_fingerprint.py", line 179, in get_image
    return self._get_packet(12)[0]
  File "/usr/local/lib/python3.9/dist-packages/adafruit_fingerprint.py", line 354, in _get_packet
    raise RuntimeError("Incorrect packet data")
RuntimeError: Incorrect packet data

**Comment by jepler** [comment]
We prefer not to use github as a support forum. If you are using hardware from Adafruit, please use the [Adafruit Customer Support Forums](https://forums.adafruit.com/index.php) to get assistance. Thank you!
