### ISSUE TITLE
Compare print to file Error

### ISSUE THREAD

**Issue by josevargasop** [adafruit/Adafruit_CircuitPython_Fingerprint#53]
I'm trying to use this [example](https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint/blob/main/examples/fingerprint_template_file_compare.py) but i get this error when I try to compare print to file.

`Waiting for finger print...
Templating...
Loading file template...Traceback (most recent call last):
  File "/home/pi/Adafruit_CircuitPython_Fingerprint/examples/fingerprint_template_file_compare.py", line 199, in <module>
    fingerprint_check_file()
  File "/home/pi/Adafruit_CircuitPython_Fingerprint/examples/fingerprint_template_file_compare.py", line 72, in fingerprint_check_file
    i = finger.compare_templates()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/adafruit_fingerprint.py", line 323, in compare_templates
    r = self._get_packet(14)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/adafruit_fingerprint.py", line 349, in _get_packet
    raise RuntimeError("Failed to read data from sensor")
RuntimeError: Failed to read data from sensor`

I'm on raspberry pi 4 with this [sensor](https://www.adafruit.com/product/4651)

All the other examples works fine.

**Comment by cvillegas2023** [comment]
I have the same error.
I tried this link, but it was not solved or I did not understand the instructions

https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint/issues/30

**Comment by josevargasop** [comment]
> I have the same error. I tried this link, but it was not solved or I did not understand the instructions
> 
> #30

Hello, do you need help? I finally solve it.

i dont remember all but I think i only write a:

 time.sleep

 before

 i = finger.compare_templates()
